<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1 Factor coding | Factor coding, contrasts, and the emmeans package</title>
  <meta name="description" content="1 Factor coding | Factor coding, contrasts, and the emmeans package" />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="1 Factor coding | Factor coding, contrasts, and the emmeans package" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://wes-brooks.github.io/workshop_factors_emmeans/" />
  
  
  <meta name="github-repo" content="wes-brooks/workshop_factors_emmeans" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1 Factor coding | Factor coding, contrasts, and the emmeans package" />
  
  
  

<meta name="author" content="Wesley Brooks" />


<meta name="date" content="2021-10-13" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="constraints.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://datalab.ucdavis.edu/">
  <img src="https://datalab.ucdavis.edu/wp-content/uploads/2019/07/datalab-logo-full-color-rgb-1.png" style="height: 100%; width: 100%; object-fit: contain" />
</a></li>
<li><a href="./" style="font-size: 18px">Factor coding, contrasts, and the `emmeans` package</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#learning-goals"><i class="fa fa-check"></i><b>0.1</b> Learning goals:</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="factor-coding.html"><a href="factor-coding.html"><i class="fa fa-check"></i><b>1</b> Factor coding</a>
<ul>
<li class="chapter" data-level="1.1" data-path="factor-coding.html"><a href="factor-coding.html#how-factors-are-coded-in-a-model"><i class="fa fa-check"></i><b>1.1</b> How factors are coded in a model</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="factor-coding.html"><a href="factor-coding.html#the-linear-algebra-explanation"><i class="fa fa-check"></i><b>1.1.1</b> The linear algebra explanation</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="factor-coding.html"><a href="factor-coding.html#the-default"><i class="fa fa-check"></i><b>1.2</b> The default</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="constraints.html"><a href="constraints.html"><i class="fa fa-check"></i><b>2</b> Constraints</a>
<ul>
<li class="chapter" data-level="2.1" data-path="constraints.html"><a href="constraints.html#contr.treatment"><i class="fa fa-check"></i><b>2.1</b> <code>contr.treatment</code></a></li>
<li class="chapter" data-level="2.2" data-path="constraints.html"><a href="constraints.html#one-hot-encoding"><i class="fa fa-check"></i><b>2.2</b> “One-hot” encoding</a></li>
<li class="chapter" data-level="2.3" data-path="constraints.html"><a href="constraints.html#contr.sum-sum-to-zero-constraints"><i class="fa fa-check"></i><b>2.3</b> <code>contr.sum</code>: sum-to-zero constraints</a></li>
<li class="chapter" data-level="2.4" data-path="constraints.html"><a href="constraints.html#contr.poly"><i class="fa fa-check"></i><b>2.4</b> <code>contr.poly</code></a></li>
<li class="chapter" data-level="2.5" data-path="constraints.html"><a href="constraints.html#contr.helmert-and-contr.sas"><i class="fa fa-check"></i><b>2.5</b> <code>contr.helmert</code> and <code>contr.SAS</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="emmeans.html"><a href="emmeans.html"><i class="fa fa-check"></i><b>3</b> <code>emmeans</code></a>
<ul>
<li class="chapter" data-level="3.1" data-path="emmeans.html"><a href="emmeans.html#simplest-case-single-factor-variable"><i class="fa fa-check"></i><b>3.1</b> Simplest case: single factor variable</a></li>
<li class="chapter" data-level="3.2" data-path="emmeans.html"><a href="emmeans.html#a-slightly-more-complex-model"><i class="fa fa-check"></i><b>3.2</b> A slightly more complex model</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Factor coding, contrasts, and the <code>emmeans</code> package</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="factor-coding" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Factor coding</h1>
<p><code>factor</code> is R’s name for a categorical variable. Let’s see an example. The <code>chickwts</code> data set is built into R, and records the results of a 1948 experiment where chicks were fed on different diets, and their weights were measured in grams at six weeks of age.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="factor-coding.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the chickwts dataset and look at the top rows</span></span>
<span id="cb1-2"><a href="factor-coding.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>( chickwts )</span>
<span id="cb1-3"><a href="factor-coding.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>( chickwts )</span></code></pre></div>
<pre><code>##   weight      feed
## 1    179 horsebean
## 2    160 horsebean
## 3    136 horsebean
## 4    227 horsebean
## 5    217 horsebean
## 6    168 horsebean</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="factor-coding.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># look at the feed variable - it&#39;s a factor</span></span>
<span id="cb3-2"><a href="factor-coding.html#cb3-2" aria-hidden="true" tabindex="-1"></a>chickwts<span class="sc">$</span>feed</span></code></pre></div>
<pre><code>##  [1] horsebean horsebean horsebean horsebean horsebean horsebean horsebean
##  [8] horsebean horsebean horsebean linseed   linseed   linseed   linseed  
## [15] linseed   linseed   linseed   linseed   linseed   linseed   linseed  
## [22] linseed   soybean   soybean   soybean   soybean   soybean   soybean  
## [29] soybean   soybean   soybean   soybean   soybean   soybean   soybean  
## [36] soybean   sunflower sunflower sunflower sunflower sunflower sunflower
## [43] sunflower sunflower sunflower sunflower sunflower sunflower meatmeal 
## [50] meatmeal  meatmeal  meatmeal  meatmeal  meatmeal  meatmeal  meatmeal 
## [57] meatmeal  meatmeal  meatmeal  casein    casein    casein    casein   
## [64] casein    casein    casein    casein    casein    casein    casein   
## [71] casein   
## Levels: casein horsebean linseed meatmeal soybean sunflower</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="factor-coding.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># make a boxplot of weight vs. feed</span></span>
<span id="cb5-2"><a href="factor-coding.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>( weight <span class="sc">~</span> feed, <span class="at">data=</span>chickwts )</span></code></pre></div>
<p><img src="01_factor_coding_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>There are six different types of feed: casein, horsebean, linseed, meatmeal, soybean, and sunflower. Now see what happens when I fit a linear model to this data:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="factor-coding.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a linear model using the default coding, look at its summary</span></span>
<span id="cb6-2"><a href="factor-coding.html#cb6-2" aria-hidden="true" tabindex="-1"></a>lm_default <span class="ot">=</span> <span class="fu">lm</span>( weight <span class="sc">~</span> feed, <span class="at">data=</span>chickwts )</span>
<span id="cb6-3"><a href="factor-coding.html#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( lm_default )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ feed, data = chickwts)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -123.909  -34.413    1.571   38.170  103.091 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    323.583     15.834  20.436  &lt; 2e-16 ***
## feedhorsebean -163.383     23.485  -6.957 2.07e-09 ***
## feedlinseed   -104.833     22.393  -4.682 1.49e-05 ***
## feedmeatmeal   -46.674     22.896  -2.039 0.045567 *  
## feedsoybean    -77.155     21.578  -3.576 0.000665 ***
## feedsunflower    5.333     22.393   0.238 0.812495    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 54.85 on 65 degrees of freedom
## Multiple R-squared:  0.5417, Adjusted R-squared:  0.5064 
## F-statistic: 15.36 on 5 and 65 DF,  p-value: 5.936e-10</code></pre>
<p>The casein feed isn’t shown in the results! And most of the feed types that are shown would give the chicks negative weights, which is clearly absurd. What gives?!</p>
<div id="how-factors-are-coded-in-a-model" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> How factors are coded in a model</h2>
<p>The short answer is that the intercept here is actually the average weight of chicks on the casein feed, and everything else is the difference from casein. So based on the first two lines of the result table, chicks on casein feed weigh 323 grams on average, and those on the horsebean feed weigh 163 grams <em>less than that</em>, or 160 grams. Those numbers shold make sense based on the boxplot.</p>
<p>But why are the results reported in such a weird way?</p>
<div id="the-linear-algebra-explanation" class="section level3" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> The linear algebra explanation</h3>
<p>Imagine that your factor variable has three levels, and call them A, B, and C. You’re estimating how a continuous variable (like chick weight) depends on the factor level (like chick feed). You typically use an intercept to represent the overall average weight (aka the “grand mean”), so that you can then test whether any factor levels are different from average. This leads to a model where the grand mean <span class="math inline">\(\mu\)</span> and the factor levels <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, and <span class="math inline">\(C\)</span> represent the average weights, with some random noise added in, too. That’s written like this:</p>
<p><img src="images/eq1.png" alt="System of equations" width="200"/></p>
<p>This system of equations can’t be solved (too many unknowns) so we work with the average of each group (A, B, C). To do so, we assume that the average error is zero within each group, so the group means can each be written as the sum of the grand mean and the group effect:</p>
<p><img src="images/eq2.png" alt="overspecified mean model" width="200"/></p>
<p>Now we are down to three equations with four unknowns - close but not good enough! Another way to write that same system of equations is this, which will be a bit more productive going forward:</p>
<p><img src="images/eq3.png" alt="overspecified mean model - linear system" width="400"/></p>
<p>We have to reduce the number of unknowns by one. We do so by introducing a constraint on the coefficients, which allows us to remove a column from the “design matrix” in the figure above.</p>
</div>
</div>
<div id="the-default" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> The default</h2>
<p>By default, R will drop the column that represents the first level of each factor. This is called a “treatment contrast” (more on contrasts later) or the set-to-zero constraint (because it is like constraining the <span class="math inline">\(A\)</span> effect to be zero):</p>
<p><img src="images/eq4.png" alt="set to zero constraint" width="400"/></p>
<p>Now we’ll look back at the model summary table, where the “first” level of the factor (casein) doesn’t appear. That’s because it is set to zero in order to estimate the model. Since casein is swept into the intercept, we find the average weight of a chick fed on horsebeans by adding the <code>(Intercept)</code> and <code>feedhorsebean</code> coefficients, as you would predict from the design matrix of the set-to-zero constraint:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="factor-coding.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># look again at the summary table for lm_default</span></span>
<span id="cb8-2"><a href="factor-coding.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( lm_default )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ feed, data = chickwts)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -123.909  -34.413    1.571   38.170  103.091 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    323.583     15.834  20.436  &lt; 2e-16 ***
## feedhorsebean -163.383     23.485  -6.957 2.07e-09 ***
## feedlinseed   -104.833     22.393  -4.682 1.49e-05 ***
## feedmeatmeal   -46.674     22.896  -2.039 0.045567 *  
## feedsoybean    -77.155     21.578  -3.576 0.000665 ***
## feedsunflower    5.333     22.393   0.238 0.812495    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 54.85 on 65 degrees of freedom
## Multiple R-squared:  0.5417, Adjusted R-squared:  0.5064 
## F-statistic: 15.36 on 5 and 65 DF,  p-value: 5.936e-10</code></pre>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="constraints.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/wes-brooks/workshop_factors_emmeans/edit/master/01_factor_coding.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/wes-brooks/workshop_factors_emmeans/blob/master/01_factor_coding.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
